# codemagic.yaml

scripts:
  - name: Install dependencies
    script: |
      # Устанавливаем зависимости
      npm install

  - name: Sync Capacitor
    script: |
      npx cap sync

  - name: Build APK
    script: |
      cd android
      ./gradlew assembleRelease
      cd ..